spring:
  application:
    name: customer-service

  data:
    mongodb:
      uri: mongodb+srv://alisa:42RfJUb1PB1nI9K2@customer-service.x4cyu.mongodb.net/customerService?retryWrites=true&w=majority

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: localhost
---
app:
  swagger-url: http://localhost:8100/swagger-ui.html

