spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb+srv://alisa:UEOCd5DLRsMOOtAp@order-service.sqbjj.mongodb.net/orderService?retryWrites=true&w=majority

server:
  port: 8300

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: localhost
